openapi: 3.0.1
info:
  title: Lime Reader
  description: 'This is a sample Lime Reader.'
  version: 1.0.0
tags:
  - name: lime
    description: The only one endpoint of Lime Reader
paths:
  /betvictor/history:
    get:
      tags:
        - lime
      summary: Lime history
      description: Returns last 10 lime history
      operationId: limeHistory
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Limes'
        404:
          description: Not found
          content: {}

components:
  schemas:
    Limes:
      type: array
      items:
        $ref: '#/components/schemas/Lime'

    Lime:
      required:
        - freq_word
        - avg_paragraph_size
        - avg_paragraph_processing_time
        - total_processing_time
      type: object
      properties:
        freq_word:
          type: string
          description: most_frequent_word
        avg_paragraph_size:
          type: integer
          format: int32
          description: avg_paragraph_size
        avg_paragraph_processing_time:
          type: number
          description: avg_paragraph_processing_time
        total_processing_time:
          type: number
          description: total_processing_time
      example:
        freq_word: "lime"
        avg_paragraph_size: 16
        avg_paragraph_processing_time: 0.123
        total_processing_time: 13.12
